//
// This file has been auto-generated by the `npm run build-styles-prism` task
//

export default [
  'atom-dark',
  'base16-ateliersulphurpool.light',
  'cb',
  'coy',
  'darcula',
  'dark',
  'duotone-dark',
  'duotone-earth',
  'duotone-forest',
  'duotone-light',
  'duotone-sea',
  'duotone-space',
  'funky',
  'ghcolors',
  'hopscotch',
  'okaidia',
  'pojoaque',
  'prism',
  'solarizedlight',
  'tomorrow',
  'twilight',
  'vs',
  'xonokai'
];
